-- Add critique_report column to theses table
ALTER TABLE theses ADD COLUMN IF NOT EXISTS critique_report TEXT;

-- Update the comments/description
COMMENT ON COLUMN theses.critique_report IS 'Stores the detailed critique report generated by the AI before content generation.';
